import Link from 'next/link';
import { ArrowRight, Check, CheckCircle2, Compass, FileText, Hotel, Mail, MapPin, Users, Waves } from 'lucide-react';
import SampleKit from '@/components/sample-kit';
import { vendors } from '@/lib/vendors';
import { guides } from '@/lib/guides';

const inclusions = [
  ['Local research you can use', 'Hotels, group dining, picnic catering, and gathering spaces—with official sources, group details, and inquiry links.'],
  ['A plan shaped around your family', 'Your headcount, dates, room needs, budget, and accessibility needs become a shortlist and an editable weekend plan.'],
  ['The words to get things moving', 'Provider-specific inquiries, follow-up drafts, and questions to ask before you commit. Review, copy, and send.'],
  ['A practical booking workbook', 'Compare replies, record quotes and deposits, check missing terms, and keep your next actions together.'],
  ['A guide for your guests', 'A downloadable weekend guide and invitation text, with email RSVP to you. Keep family questions out of scattered threads.'],
  ['Your whole kit to keep', 'Download the organizer plan, contacts, spreadsheets, email drafts, day-of notes, guest guide, and a restorable backup.'],
];
const faqs = [
  ['What makes this worth $39?', 'The aim is to take the groundwork off your plate: a researched local starting point, prepared outreach, and the documents that carry a reunion from idea to weekend. Inspect the sample and working preview to judge the value for your family. The planned paid price is $39 once per reunion; checkout is not open yet.'],
  ['Are these places actually researched?', 'Yes. The current edition includes 11 local options researched from official provider and public-agency sources, checked September 6, 2026. Each record links to its source. We distinguish published facts from details you still need to confirm. Inclusion is not a personal endorsement or a booking.'],
  ['Do you make the reservations for me?', 'You choose the places, review and send the prepared inquiries, receive replies in your own inbox, and confirm reservations directly. The kit organizes that work. Hotel, food, venue, permit, and other provider charges are separate.'],
  ['Does it include current prices?', 'Where useful public prices are available, we label them with a source and check date. Most group hotel, restaurant, and venue arrangements need a quote for your dates, layout, and headcount. Your inquiries ask for a complete price, and the workbook helps you compare replies.'],
  ['Can I start if our dates or numbers are uncertain?', 'Yes. Leave dates flexible and use your best estimate for headcount. Update your details as plans settle. Reconfirm provider quotes whenever your dates or group requirements change.'],
  ['How do I share it with my family?', 'Download and share the guest-guide file and invitation text. Add your organizer email for email RSVPs. The guide is a snapshot you can resend when plans change. Hosted guest websites, shared accounts, and automatic RSVP tracking are not included in this preview. Your working plan saves on this device; download a backup to move it.'],
];

export default function Home() {
  return <div className="marketing">
    <a className="mk-skip" href="#main">Skip to content</a>
    <header className="mk-nav"><Link href="/" className="brand" aria-label="Santa Cruz Reunion Kit home"><span className="brand-icon"><Waves size={24}/></span><span>Santa Cruz<span className="brand-sub">REUNION KIT</span></span></Link><nav aria-label="Main navigation"><a href="#included">The kit</a><Link href="/guides">Local guides</Link><a href="#price">Pricing</a><Link href="/plan" className="mk-nav-plan">Open planner <ArrowRight size={15}/></Link></nav></header>
    <main id="main">
      <section className="mk-hero mk-wrap">
        <div className="mk-hero-copy"><p className="mk-label">SANTA CRUZ FAMILY REUNION PLANNING</p><h1>A whole reunion to plan.<br/><em>A lot less to figure out.</em></h1><p className="mk-lede">The local places. The group details. The emails to get things moving. A personalized planning kit for the family member making it all happen.</p><div className="mk-hero-actions"><Link href="/plan?start=1" className="mk-button">Build my reunion preview <ArrowRight size={18}/></Link><a href="#sample" className="mk-text-link">Look inside the kit</a></div><p className="mk-micro">Free working preview · No account or card required</p><div className="mk-hero-price"><span>THE COMPLETE PLANNING KIT</span><p><strong>$39</strong> planned one-time price per reunion</p></div></div>
        <div className="mk-hero-art"><img src="/images/santa-cruz-coast.jpg" alt="Waves meeting the cliffs along the Santa Cruz coast" fetchPriority="high" width="1100" height="733"/><div className="mk-art-caption"><MapPin size={13}/> A LITTLE TIME TOGETHER, BY THE COAST</div><div className="mk-paper"><div className="mk-paper-top"><Waves size={23}/><span>YOUR REUNION<br/>STARTS HERE</span></div><h2>From “we should”<br/>to “see you there.”</h2><ul><li><CheckCircle2 size={17}/> Places that fit your group</li><li><CheckCircle2 size={17}/> Inquiries ready to personalize</li><li><CheckCircle2 size={17}/> One plan to bring it together</li></ul><div className="mk-paper-bottom"><span>LOCAL RESEARCH + YOUR FAMILY</span><Compass size={22}/></div></div></div>
      </section>
      <div className="mk-proof-strip"><div className="mk-wrap"><span><MapPin size={18}/><strong>{vendors.length} researched local options</strong></span><span><CheckCircle2 size={18}/> Official sources & check dates</span><span><FileText size={18}/> A complete sample you can inspect</span></div></div>
      <section className="mk-section mk-wrap" id="included"><div className="mk-section-head"><p className="mk-label">YOU BRING THE FAMILY. START WITH THE GROUNDWORK.</p><h2>Less searching and second-guessing.<br/>More of the pieces, already together.</h2><p>Which hotel handles groups? Can a restaurant seat everyone? What do you ask before paying a deposit? Start with useful answers—and prepared questions for the rest.</p></div><div className="mk-inclusions">{inclusions.map(([title, description], i) => <article key={title}><span className="mk-item-number">0{i+1}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>
      <section className="mk-sample-section" id="sample"><div className="mk-wrap"><div className="mk-section-head"><p className="mk-label">OPEN IT. SEE THE WORK.</p><h2>Here’s what a head start looks like.</h2><p>Explore the shortlist, read an actual prepared inquiry, and see what your family receives. The sample download is yours to inspect.</p></div><SampleKit/></div></section>
      <section className="mk-section mk-wrap mk-how"><div><p className="mk-label">FROM IDEA TO INQUIRIES</p><h2>You don’t need<br/>every answer yet.</h2><p>Start with what you know. Your kit gives the next conversation somewhere to begin.</p><Link href="/plan?start=1" className="mk-text-link">Make a plan for my family <ArrowRight size={16}/></Link></div><ol><li><span>01</span><div><h3>Tell us about your people.</h3><p>Dates, group size, budget, and the kind of weekend you want. Estimates are welcome.</p></div></li><li><span>02</span><div><h3>Shape your local shortlist.</h3><p>Review researched options and personalized inquiries. Choose the places that feel right.</p></div></li><li><span>03</span><div><h3>Send, compare, and bring it together.</h3><p>Send inquiries yourself, record replies, confirm bookings with providers, and share your guest guide.</p></div></li></ol></section>
      <section className="mk-story"><div className="mk-wrap"><span className="mk-story-mark"><Users size={35}/></span><div><p className="mk-label">BUILT FROM OUR OWN FAMILY REUNION</p><h2>We were the family<br/>trying to figure it all out.</h2><p>After organizing a Santa Cruz reunion for about 100 relatives, we wanted the next family organizer to have a better starting point: local options, practical questions, and the pieces that keep the weekend moving.</p><p className="mk-story-credit">The idea behind Santa Cruz Reunion Kit</p></div></div></section>
      <section className="mk-section mk-wrap mk-pricing" id="price"><div><p className="mk-label">ONE REUNION. ONE PLANNING KIT.</p><h2>The research is visible.<br/>So is the price.</h2><p>Judge the kit by the work it helps you do: find suitable places, ask useful questions, compare real replies, and keep your people informed.</p><div className="mk-price-example"><Users size={23}/><p>Shared across <strong>20 households</strong>, a $39 kit would be <strong>$1.95 per household</strong>.<small>Illustrative cost split for the planning kit only.</small></p></div></div><article className="mk-price-card"><p className="mk-label">THE COMPLETE PLANNING KIT</p><div className="mk-price"><span>$39</span><p>Planned price<br/>Once per reunion</p></div><p className="mk-price-description">Local groundwork, shaped around your family.</p><ul>{['All 11 researched local options','Personalized plan & provider inquiries','Follow-up and booking-check templates','Quote, deposit & decision workbook','Guest guide, invitation & day-of notes','Downloadable kit and backup'].map(text => <li key={text}><Check size={17}/>{text}</li>)}</ul><Link href="/plan?start=1" className="mk-button">Try the working preview <ArrowRight size={17}/></Link><p className="mk-price-status">The preview is free today. Paid checkout is not open yet.</p><small>Provider charges are separate. You send inquiries and confirm bookings directly.</small></article></section>
      <section className="mk-section mk-wrap mk-guides"><div className="mk-section-head"><p className="mk-label">A LITTLE LOCAL KNOW-HOW</p><h2>Start with your biggest question.</h2></div><div>{guides.map((guide,i)=><Link href={`/guides/${guide.slug}`} key={guide.slug}><span>{i===0?<MapPin size={23}/>:i===1?<Users size={23}/>:<Hotel size={23}/>}</span><h3>{guide.shortTitle}</h3><p>{guide.description}</p><strong>Read the guide <ArrowRight size={16}/></strong></Link>)}</div></section>
      <section className="mk-section mk-wrap mk-faq"><div><p className="mk-label">BEFORE YOU START</p><h2>A few good questions.</h2></div><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="mk-final"><p className="mk-label">YOUR PEOPLE. YOUR WEEKEND.</p><h2>Give your reunion<br/>a real starting point.</h2><Link href="/plan?start=1" className="mk-button mk-button-cream">Build my reunion preview <ArrowRight size={18}/></Link><p>Start free. Bring what you know. Keep making it yours.</p></section>
    </main>
    <footer className="mk-footer mk-wrap"><div><Link href="/" className="brand">Santa Cruz<span className="brand-sub">REUNION KIT</span></Link><p>Made for getting together.</p></div><nav aria-label="Footer navigation"><Link href="/guides">Planning guides</Link><Link href="/plan">Your planner</Link><a href="#price">Pricing</a><a href="https://unsplash.com/photos/qR5wQNyDA1s" target="_blank" rel="noreferrer">Photo: Sean Kelley</a></nav><small>Research checked September 6, 2026. Confirm availability and complete terms with each provider.</small></footer>
  </div>;
}
