import type { Vendor } from './planner';

// Researched from official sources; these records do not imply personal vetting,
// live availability, a booking, or an event-specific quote.
export const vendors: Vendor[] = [
  {
    id: 'dream-inn', name: 'Dream Inn Santa Cruz', category: 'hotel',
    location: '175 W Cliff Drive, Santa Cruz, CA 95060',
    description: 'Beachfront lodging and ocean-view gathering rooms, with an event inquiry form that explicitly welcomes family reunions.',
    capacity: null,
    url: 'https://www.dreaminnsantacruz.com/meetings/rfp',
    priceNote: 'Request a dated room-block and event quote. Room rates, catering, parking, taxes and any minimums must be confirmed.',
    highlights: ['Ocean-view event spaces', 'Family reunion inquiries welcomed', 'Ask for the right room layout for your headcount'],
    source: 'https://www.dreaminnsantacruz.com/meetings/overview', checkedAt: '2026-09-06',
  },
  {
    id: 'seascape', name: 'Seascape Beach Resort', category: 'hotel',
    location: 'One Seascape Resort Drive, Aptos, CA 95003',
    description: 'A coastal resort with suites, villas and several gathering rooms. The Pacific Room lists capacity for 110 at rounds; other layouts vary.',
    capacity: null,
    url: 'https://seascaperesort.com/meetings-conferences',
    priceNote: 'Group lodging and event pricing require a quote. Ask about minimum stays, resort fees and food-and-beverage commitments.',
    highlights: ['Suites and villas', 'On-site catering', 'Inquiry form for meeting space and guestrooms'],
    source: 'https://seascaperesort.com/meetings-conferences', checkedAt: '2026-09-06',
  },
  {
    id: 'chaminade', name: 'Chaminade Resort & Spa', category: 'hotel',
    location: 'One Chaminade Lane, Santa Cruz, CA 95065',
    description: 'A hilltop resort with flexible gathering spaces and an on-site group sales team. Ask for a family reunion package tailored to your weekend.',
    capacity: null, email: 'sales@chaminade.com',
    url: 'https://www.chaminade.com/santacruz-meetings/submit-rfp/',
    priceNote: 'Request group room rates and a separate event quote. Published conference packages are not reunion-specific prices.',
    highlights: ['Group sales contact available', 'Catering and gathering spaces', 'Day-event options without overnight lodging'],
    source: 'https://www.chaminade.com/santacruz-meetings/benchmark-conference-plan/', checkedAt: '2026-09-06',
  },
  {
    id: 'shadowbrook', name: 'Shadowbrook Restaurant', category: 'restaurant',
    location: '1750 Wharf Road, Capitola, CA',
    description: 'Creekside private dining in several distinctive rooms. The Wine Cellar seats up to 35; larger parties may use multiple rooms by arrangement.',
    capacity: null, email: 'banquets@shadowbrook-capitola.com',
    url: 'https://shadowbrook-capitola.com/private-events/',
    priceNote: 'Private-event menus, guest minimums and prices are available by inquiry. Request the full price including taxes and service charges.',
    highlights: ['Four private dining rooms', 'Groups over 16 use banquet coordination', 'Confirm a single-room or multi-room layout'],
    source: 'https://shadowbrook-capitola.com/private-events/', checkedAt: '2026-09-06',
  },
  {
    id: 'crows-nest', name: "The Crow’s Nest — Harbor Room", category: 'restaurant',
    location: '2218 East Cliff Drive, Santa Cruz, CA 95062',
    description: 'A private downstairs waterfront room overlooking the harbor, with seating for up to 50 guests and a dedicated banquet contact.',
    capacity: 50, email: 'events@crowsnest-santacruz.com',
    url: 'https://crowsnest-santacruz.com/santa-cruz-the-crows-nest-party',
    priceNote: 'Request a private-party quote and confirm room fees, minimum spend, tax and gratuity. Published menus are reference prices, not a reservation.',
    highlights: ['Harbor Room seats up to 50', 'Waterfront private dining', 'Large-party arrangements up to a year ahead'],
    source: 'https://crowsnest-santacruz.com/', checkedAt: '2026-09-06',
  },
  {
    id: 'hindquarter', name: 'Hindquarter Bar & Grille', category: 'restaurant',
    location: 'Santa Cruz, CA — confirm arrival address with restaurant',
    description: 'A local grill offering special events and custom menus. Contact the team to check whether your party size and preferred format fit.',
    capacity: null, email: 'info@hindquarterbg.com',
    url: 'https://www.thehindquarter.com/',
    priceNote: 'Custom event quote required. Dining-menu specials do not establish a group price or available capacity.',
    highlights: ['Special events offered', 'Custom menu inquiries', 'Confirm capacity and private-space options'],
    source: 'https://www.thehindquarter.com/', checkedAt: '2026-09-06',
  },
  {
    id: 'roaring-camp', name: 'Roaring Camp Railroads', category: 'venue',
    location: '5401 Graham Hill Road, Felton, CA 95018',
    description: 'Redwood picnic grounds, an event hall and train experiences, with a group program that explicitly includes family reunions.',
    capacity: null,
    url: 'https://roaringcamp.com/contactinfo',
    priceNote: 'Ask group sales for picnic-space, food and train pricing separately, including any minimums and cancellation terms.',
    highlights: ['Reunion group program', 'Indoor and outdoor options', 'Choose a specific picnic site before confirming capacity'],
    source: 'https://roaringcamp.com/group-activities', checkedAt: '2026-09-06',
  },
  {
    id: 'delaveaga', name: 'DeLaveaga Park — Forty Thieves', category: 'venue',
    location: '855 Branciforte Drive, Santa Cruz, CA',
    description: 'A reservable picnic area for up to 100, with grills, drinking water, accessible bathrooms and accessible parking.',
    capacity: 100, email: 'parksandrec@santacruzca.gov',
    url: 'https://www.santacruzca.gov/Government/City-Departments/Parks-Recreation/Events/Reservation-Office-Event-Permits/Private-Events-Reservations/Picnic-Areas',
    priceNote: 'Confirm the current fee and available date with City Parks. Rate categories and added permits can change the total.',
    highlights: ['Capacity: 100', 'Grills and picnic tables', 'George Washington Grove closes November 1 through March 1'],
    source: 'https://www.santacruzca.gov/Government/City-Departments/Parks-Recreation/Parks-Beaches-Open-Spaces/Parks/DeLaveaga-Park', checkedAt: '2026-09-06',
  },
  {
    id: 'twin-lakes', name: 'Twin Lakes State Beach', category: 'venue',
    location: 'East Cliff Drive / Portola Drive shoreline, Santa Cruz, CA',
    description: 'A beach gathering option near the harbor. Speak with State Parks about the exact event footprint, permitted activities and access.',
    capacity: null, email: 'SCD.specialevents@parks.ca.gov',
    url: 'https://www.parks.ca.gov/?page_id=547',
    priceNote: 'Ask State Parks for event eligibility, permit fees and conditions. No private beach closure or reserved capacity is promised.',
    highlights: ['Official special-event contact', '2026 event application linked on park page', 'Confirm parking, accessibility and permitted setup'],
    source: 'https://www.parks.ca.gov/?page_id=547', checkedAt: '2026-09-06',
  },
  {
    id: 'seacliff', name: 'Seacliff State Beach', category: 'venue',
    location: 'Seacliff State Beach, Aptos, CA — confirm event meeting point',
    description: 'A beach and picnic setting in the Aptos area. The park provides a dedicated special-events contact and a current application link.',
    capacity: null, email: 'SCD.specialevents@parks.ca.gov',
    url: 'https://www.parks.ca.gov/SeacliffStateBeach',
    priceNote: 'Request permit details and current fees directly. Check current access restrictions and the exact picnic area before inviting guests.',
    highlights: ['Beach and picnic setting', 'Official special-event application', 'Published park hours: 8 a.m. to sunset'],
    source: 'https://www.parks.ca.gov/SeacliffStateBeach', checkedAt: '2026-09-06',
  },
  {
    id: 'zoccolis', name: "Zoccoli’s Deli — Picnic Catering", category: 'restaurant',
    location: '1534 Pacific Avenue, Santa Cruz, CA 95060',
    description: 'Downtown deli with a catering menu: a useful lead for a picnic meal or welcome lunch. Call 831-423-1711 to discuss the order.',
    capacity: null,
    url: 'https://www.zoccolis.com/catering',
    priceNote: 'Confirm current catering prices, order lead time, portions, dietary needs and pickup or delivery arrangements by phone.',
    highlights: ['Catering menu available', 'Downtown pickup location', 'Picnic-food option; no group seating capacity confirmed'],
    source: 'https://www.zoccolis.com/catering', checkedAt: '2026-09-06',
  },
];
