import type { Vendor } from './planner';

// Researched from official sources; these records do not imply personal vetting,
// live availability, a booking, or an event-specific quote.
export const vendors: Vendor[] = [
  {
    id: 'dream-inn', name: 'Dream Inn Santa Cruz', category: 'hotel',
    location: '175 W Cliff Drive, Santa Cruz, CA 95060',
    description: 'Beachfront lodging and ocean-view gathering rooms, with an event inquiry form that explicitly welcomes family reunions.',
    capacity: null,
    url: 'https://www.dreaminnsantacruz.com/meetings/rfp',
    priceNote: 'Request a dated room-block and event quote. Room rates, catering, parking, taxes and any minimums must be confirmed.',
    highlights: ['Ocean-view event spaces', 'Family reunion inquiries welcomed', 'Ask for the right room layout for your headcount'],
    source: 'https://www.dreaminnsantacruz.com/meetings/overview', checkedAt: '2026-09-06',
  },
  {
    id: 'seascape', name: 'Seascape Beach Resort', category: 'hotel',
    location: 'One Seascape Resort Drive, Aptos, CA 95003',
    description: 'A coastal resort with suites, villas and several gathering rooms. The Pacific Room lists capacity for 110 at rounds; other layouts vary.',
    capacity: null,
    url: 'https://seascaperesort.com/meetings-conferences',
    priceNote: 'Group lodging and event pricing require a quote. Ask about minimum stays, resort fees and food-and-beverage commitments.',
    highlights: ['Suites and villas', 'On-site catering', 'Inquiry form for meeting space and guestrooms'],
    source: 'https://seascaperesort.com/meetings-conferences', checkedAt: '2026-09-06',
  },
  {
    id: 'chaminade', name: 'Chaminade Resort & Spa', category: 'hotel',
    location: 'One Chaminade Lane, Santa Cruz, CA 95065',
    description: 'A hilltop resort with flexible gathering spaces and an on-site group sales team. Ask for a family reunion package tailored to your weekend.',
    capacity: null, email: 'sales@chaminade.com',
    url: 'https://www.chaminade.com/santacruz-meetings/submit-rfp/',
    priceNote: 'Request group room rates and a separate event quote. Published conference packages are not reunion-specific prices.',
    highlights: ['Group sales contact available', 'Catering and gathering spaces', 'Day-event options without overnight lodging'],
    source: 'https://www.chaminade.com/santacruz-meetings/benchmark-conference-plan/', checkedAt: '2026-09-06',
  },
  {
    id: 'shadowbrook', name: 'Shadowbrook Restaurant', category: 'restaurant',
    location: '1750 Wharf Road, Capitola, CA',
    description: 'Creekside private dining with room-specific layouts. The Wine Cellar seats up to 35; the restaurant describes arrangements for 50+ across multiple rooms. Ask which configuration fits your family.',
    capacity: null, email: 'banquets@shadowbrook-capitola.com',
    url: 'https://shadowbrook-capitola.com/private-events/',
    priceNote: 'Private-event menus, guest minimums and prices are available by inquiry. Request the full price including taxes and service charges.',
    highlights: ['Wine Cellar: up to 35 seated', 'Redwood Room: 17–26 seated, depending on layout', 'Owner’s Private Reserve: up to 16 seated', '50+ across rooms; confirm configuration and exclusive use', 'Banquet inquiries: 831-475-1222'],
    source: 'https://shadowbrook-capitola.com/private-events/', checkedAt: '2026-09-06',
  },
  {
    id: 'crows-nest', name: "The Crow’s Nest — Harbor Room", category: 'restaurant',
    location: '2218 East Cliff Drive, Santa Cruz, CA 95062',
    description: 'A private downstairs waterfront room overlooking the harbor, with seating for up to 50 guests and a dedicated banquet contact.',
    capacity: 50, email: 'events@crowsnest-santacruz.com',
    url: 'https://crowsnest-santacruz.com/santa-cruz-the-crows-nest-party',
    priceNote: 'Request a private-party quote and confirm room fees, minimum spend, tax and gratuity. Published menus are reference prices, not a reservation.',
    highlights: ['Harbor Room seats up to 50', 'Waterfront private dining', 'Large-party arrangements up to a year ahead'],
    source: 'https://crowsnest-santacruz.com/', checkedAt: '2026-09-06',
  },
  {
    id: 'hindquarter', name: 'Hindquarter Bar & Grille', category: 'restaurant',
    location: '303 Soquel Avenue, Santa Cruz, CA 95062',
    description: 'A local grill offering special events and custom menus. Contact the team to check whether your party size and preferred format fit.',
    capacity: null, email: 'info@hindquarterbg.com',
    url: 'https://www.thehindquarter.com/',
    priceNote: 'Custom event quote required. Dining-menu specials do not establish a group price or available capacity.',
    highlights: ['Special events and custom menus', 'Call 831-426-7770 to confirm the requested date', 'Online reservation enters a waiting list; it is not confirmation'],
    source: 'https://www.thehindquarter.com/', checkedAt: '2026-09-06',
  },
  {
    id: 'roaring-camp', name: 'Roaring Camp Railroads', category: 'venue',
    location: '5401 Graham Hill Road, Felton, CA 95018',
    description: 'Redwood picnic grounds, an event hall and train experiences, with a group program that explicitly includes family reunions.',
    capacity: null,
    url: 'https://roaringcamp.com/contactinfo',
    priceNote: 'Ask group sales for picnic-space, food and train pricing separately, including any minimums and cancellation terms.',
    highlights: ['Reunion group program', 'Indoor and outdoor options', 'Choose a specific picnic site before confirming capacity'],
    source: 'https://roaringcamp.com/group-activities', checkedAt: '2026-09-06',
  },
  {
    id: 'delaveaga', name: 'DeLaveaga Park — Forty Thieves', category: 'venue',
    location: '855 Branciforte Drive, Santa Cruz, CA',
    description: 'A reservable picnic area for up to 100, with grills, drinking water, accessible bathrooms and accessible parking.',
    capacity: 100, email: 'parksandrec@santacruzca.gov',
    url: 'https://www.santacruzca.gov/Government/City-Departments/Parks-Recreation/Events/Reservation-Office-Event-Permits/Private-Events-Reservations/Picnic-Areas',
    priceNote: 'City fee schedule effective January 5, 2026: $251/day for City residents or $327/day for nonresidents. This is the standard site fee, not an all-in event price; added permits and deposits may apply.',
    highlights: ['Capacity: 100', 'Grills and picnic tables', 'Confirm Forty Thieves access and reservation hours'],
    source: 'https://www.santacruzca.gov/Government/City-Departments/Parks-Recreation/Parks-Beaches-Open-Spaces/Parks/DeLaveaga-Park', checkedAt: '2026-09-06',
  },
  {
    id: 'twin-lakes', name: 'Twin Lakes State Beach', category: 'venue',
    location: 'East Cliff Drive / Portola Drive shoreline, Santa Cruz, CA',
    description: 'A beach gathering option near the harbor. Speak with State Parks about the exact event footprint, permitted activities and access.',
    capacity: null, email: 'SCD.specialevents@parks.ca.gov',
    url: 'https://www.parks.ca.gov/?page_id=547',
    priceNote: 'Ask State Parks for event eligibility, permit fees and conditions. No private beach closure or reserved capacity is promised.',
    highlights: ['Official special-event contact', '2026 event application linked on park page', 'Confirm parking, accessibility and permitted setup'],
    source: 'https://www.parks.ca.gov/?page_id=547', checkedAt: '2026-09-06',
  },
  {
    id: 'seacliff', name: 'Seacliff State Beach', category: 'venue',
    location: 'Seacliff State Beach, Aptos, CA — confirm event meeting point',
    description: 'A beach and picnic setting in the Aptos area. The park provides a dedicated special-events contact and a current application link.',
    capacity: null, email: 'SCD.specialevents@parks.ca.gov',
    url: 'https://www.parks.ca.gov/SeacliffStateBeach',
    priceNote: 'Request permit details and current fees directly. Check current access restrictions and the exact picnic area before inviting guests.',
    highlights: ['Beach and picnic setting', 'Official special-event application', 'Published park hours: 8 a.m. to sunset'],
    source: 'https://www.parks.ca.gov/SeacliffStateBeach', checkedAt: '2026-09-06',
  },
  {
    id: 'zoccolis', name: "Zoccoli’s Deli — Picnic Catering", category: 'restaurant',
    location: '1534 Pacific Avenue, Santa Cruz, CA 95060',
    description: 'Off-site food for a reunion picnic or welcome lunch, with bag lunches, sandwich trays and platters. Call 831-423-1711 to arrange quantities and pickup; this is a catering lead, not a seated group venue.',
    capacity: null,
    url: 'https://www.zoccolis.com/catering',
    priceNote: 'Menu checked September 6, 2026: bag lunch $15.95; tray of 20 half sandwiches $109; meat-and-cheese platter $75 (serves 15–20). Reference menu prices, not an all-in group quote. Confirm portions, taxes, fees and current prices.',
    highlights: ['Off-site catering; confirm pickup or any delivery option', '20 half sandwiches are not 20 full sandwiches', 'Hot entrees and desserts require 48 hours’ notice', 'Confirm dietary needs, serving supplies and order deadline'],
    source: 'https://www.zoccolis.com/catering', checkedAt: '2026-09-06',
  },
  {
    id: 'hampton-santa-cruz', name: 'Hampton Inn Santa Cruz', category: 'hotel',
    location: '1505 Ocean Street, Santa Cruz, CA 95060',
    description: 'An Ocean Street hotel with included hot breakfast and parking. Its official group program offers online blocks of 10–25 rooms and an attendee booking page, subject to dates and terms.',
    capacity: null, email: 'SRUHH_Hampton@hilton.com',
    url: 'https://www.hilton.com/en/hotels/sruhhhx-hampton-santa-cruz/',
    priceNote: 'Dated group rate required. Breakfast and self-parking are listed as included; confirm tax, room types, release dates and cancellation terms. No nightly budget fit is assumed.',
    highlights: ['10–25-room online group-block route', 'Included hot breakfast and self-parking', 'Official attendee hotel-booking page option', 'Hotel contact: 831-457-8000'],
    source: 'https://www.hilton.com/en/hotels/sruhhhx-hampton-santa-cruz/', checkedAt: '2026-09-06',
  },
  {
    id: 'hyatt-place', name: 'Hyatt Place Santa Cruz', category: 'hotel',
    location: '407 Broadway Avenue, Santa Cruz, CA 95060',
    description: 'A downtown-area hotel offering room blocks and a combined event space for up to 80 attendees. Documented accessible routes connect the entrance, guestrooms, dining and meeting areas.',
    capacity: null,
    url: 'https://www.hyatt.com/hyatt-place/en-US/sjczs-hyatt-place-santa-cruz/meetings',
    priceNote: 'Ask for room-block rates and parking or breakfast inclusions in writing. The advertised 80-person event maximum is not an overnight-room inventory or a guaranteed seated dinner layout.',
    highlights: ['Group room blocks offered', 'Two meeting rooms combine for up to 80 attendees', 'Published accessible routes and public restrooms', 'Sales inquiries: 831-226-2300'],
    source: 'https://www.hyatt.com/hyatt-place/en-US/sjczs-hyatt-place-santa-cruz', checkedAt: '2026-09-06',
  },
  {
    id: 'fairfield-capitola', name: 'Fairfield Inn & Suites Santa Cruz–Capitola', category: 'hotel',
    location: '1255 41st Avenue, Capitola, CA 95010',
    description: 'An all-suite lodging alternative with a published room-block contact route. Its separate meeting room lists 70 for banquet seating; accessible parking, entrance and meeting-space routes are documented.',
    capacity: null,
    url: 'https://www.marriott.com/en-us/hotels/sjccp-fairfield-inn-and-suites-santa-cruz-capitola/events/',
    priceNote: 'Request dates, suite occupancy and the full room-block cost directly. Published inventory is 84 suites, not a promise that all suites are available to your group.',
    highlights: ['84-suite property; block availability must be quoted', 'Meeting room: 70 banquet seats', 'Documented accessible entrance and meeting spaces', 'Hotel contact: 831-427-2900'],
    source: 'https://www.marriott.com/en-us/hotels/sjccp-fairfield-inn-and-suites-santa-cruz-capitola/rooms/', checkedAt: '2026-09-06',
  },
];
